---
abstract: "An interface to Amazon's Route53"
author:
  - 'Chris Weyl <cweyl@alumni.drew.edu>'
build_requires:
  Net::DNS: 0
  Net::DNS::ZoneFile: 0
  Path::Class: 0
  Readonly: 0
  Test::Fatal: 0
  Test::More: 0.88
  Test::Requires: 0
  Tie::IxHash: 0
  strict: 0
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
  File::ShareDir::Install: 0.03
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: lgpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-Amazon-R53
no_index:
  directory:
    - corpus
    - t
provides:
  Net::Amazon::R53:
    file: lib/Net/Amazon/R53.pm
    version: 0.001
  Net::Amazon::R53::AtomicChange:
    file: lib/Net/Amazon/R53/AtomicChange.pm
    version: 0.001
  Net::Amazon::R53::ChangeInfo:
    file: lib/Net/Amazon/R53/ChangeInfo.pm
    version: 0.001
  Net::Amazon::R53::HostedZone:
    file: lib/Net/Amazon/R53/HostedZone.pm
    version: 0.001
  Net::Amazon::R53::ResourceRecordSet:
    file: lib/Net/Amazon/R53/ResourceRecordSet.pm
    version: 0.001
  Net::Amazon::R53::ResourceRecordSet::Change:
    file: lib/Net/Amazon/R53/ResourceRecordSet/Change.pm
    version: 0.001
  Net::Amazon::R53::ResourceRecordSet::Stub:
    file: lib/Net/Amazon/R53/ResourceRecordSet/Stub.pm
    version: 0.001
  Net::Amazon::R53::Role::NewFromRawData:
    file: lib/Net/Amazon/R53/Role/NewFromRawData.pm
    version: 0.001
  Net::Amazon::R53::Role::ParentR53:
    file: lib/Net/Amazon/R53/Role/ParentR53.pm
    version: 0.001
requires:
  Data::Compare: 0
  Data::UUID: 0
  File::ShareDir::ProjectDistDir: 0
  HTTP::Request: 0
  LWP::UserAgent: 0
  List::AllUtils: 0
  Moose: 0
  Moose::Autobox: 0
  Moose::Role: 0
  Moose::Util::TypeConstraints: 0
  MooseX::AlwaysCoerce: 0
  MooseX::AttributeShortcuts: 0.017
  MooseX::CascadeClearing: 0
  MooseX::CoercePerAttribute: 0
  MooseX::MarkAsMethods: 0
  MooseX::Params::Validate: 0
  MooseX::RelatedClasses: 0
  MooseX::StrictConstructor: 0
  MooseX::Traitor: 0
  MooseX::Types::Common::Numeric: 0
  MooseX::Types::Common::String: 0
  MooseX::Types::Moose: 0
  MooseX::Types::Path::Class: 0
  MooseX::Types::VariantTable: 0
  Net::Amazon::Signature::V3: 0
  Net::DNS: 0.71
  String::CamelCase: 0
  Template: 0
  XML::Simple: 0
  aliased: 0
  autobox::Core: 0
  constant: 0
  namespace::autoclean: 0
  overload: 0
  perl: v5.10.0
  utf8: 0
resources: {}
version: 0.001
x_Dist_Zilla:
  perl:
    version: 5.016001
  plugins:
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: '@RSRCHBOY/NextRelease'
      version: 4.300028
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: '@RSRCHBOY/@Git/Check'
      version: 2.005
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: '@RSRCHBOY/@Git/Commit'
      version: 2.005
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@RSRCHBOY/@Git/Tag'
      version: 2.005
    -
      class: Dist::Zilla::Plugin::Git::Push
      name: '@RSRCHBOY/@Git/Push'
      version: 2.005
    -
      class: Dist::Zilla::Plugin::Git::NextVersion
      name: '@RSRCHBOY/Git::NextVersion'
      version: 2.005
    -
      class: Dist::Zilla::Plugin::ContributorsFromGit
      name: '@RSRCHBOY/ContributorsFromGit'
      version: 0.002
    -
      class: Dist::Zilla::Plugin::Git::CheckFor::CorrectBranch
      name: '@RSRCHBOY/@Git::CheckFor/Git::CheckFor::CorrectBranch'
      version: 0.006
    -
      class: Dist::Zilla::Plugin::Git::CheckFor::Fixups
      name: '@RSRCHBOY/@Git::CheckFor/Git::CheckFor::Fixups'
      version: 0.006
    -
      class: Dist::Zilla::Plugin::Git::CheckFor::MergeConflicts
      name: '@RSRCHBOY/@Git::CheckFor/Git::CheckFor::MergeConflicts'
      version: 0.006
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: '@RSRCHBOY/GatherDir'
      version: 4.300028
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@RSRCHBOY/PruneCruft'
      version: 4.300028
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@RSRCHBOY/ExecDir'
      version: 4.300028
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@RSRCHBOY/ShareDir'
      version: 4.300028
    -
      class: Dist::Zilla::Plugin::MakeMaker
      name: '@RSRCHBOY/MakeMaker'
      version: 4.300028
    -
      class: Dist::Zilla::Plugin::InstallGuide
      name: '@RSRCHBOY/InstallGuide'
      version: 1.200000
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@RSRCHBOY/Manifest'
      version: 4.300028
    -
      class: Dist::Zilla::Plugin::SurgicalPkgVersion
      name: '@RSRCHBOY/SurgicalPkgVersion'
      version: 0.0019
    -
      class: Dist::Zilla::Plugin::ReadmeFromPod
      name: '@RSRCHBOY/ReadmeFromPod'
      version: 0.16
    -
      class: Dist::Zilla::Plugin::MinimumPerl
      name: '@RSRCHBOY/MinimumPerl'
      version: 1.003
    -
      class: Dist::Zilla::Plugin::ReportVersions::Tiny
      name: '@RSRCHBOY/ReportVersions::Tiny'
      version: 1.08
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: '@RSRCHBOY/AutoPrereqs'
      version: 4.300028
    -
      class: Dist::Zilla::Plugin::Prepender
      name: '@RSRCHBOY/Prepender'
      version: 1.112280
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@RSRCHBOY/MetaConfig'
      version: 4.300028
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@RSRCHBOY/MetaJSON'
      version: 4.300028
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@RSRCHBOY/MetaYAML'
      version: 4.300028
    -
      class: Dist::Zilla::Plugin::MetaNoIndex
      name: '@RSRCHBOY/MetaNoIndex'
      version: 4.300028
    -
      class: Dist::Zilla::Plugin::MetaProvides::Package
      name: '@RSRCHBOY/MetaProvides::Package'
      version: 1.14000001
    -
      class: Dist::Zilla::Plugin::GitHub::Meta
      name: '@RSRCHBOY/GitHub::Meta'
      version: 0.29
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@RSRCHBOY/TestRelease'
      version: 4.300028
    -
      class: Dist::Zilla::Plugin::CheckChangesHasContent
      name: '@RSRCHBOY/CheckChangesHasContent'
      version: 0.006
    -
      class: Dist::Zilla::Plugin::CheckPrereqsIndexed
      name: '@RSRCHBOY/CheckPrereqsIndexed'
      version: 0.007
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@RSRCHBOY/ConfirmRelease'
      version: 4.300028
    -
      class: Dist::Zilla::Plugin::GitHub::Update
      name: '@RSRCHBOY/GitHub::Update'
      version: 0.29
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@RSRCHBOY/UploadToCPAN'
      version: 4.300028
    -
      class: Dist::Zilla::Plugin::Signature
      name: '@RSRCHBOY/Signature'
      version: 1.100930
    -
      class: Dist::Zilla::Plugin::InstallRelease
      name: '@RSRCHBOY/InstallRelease'
      version: 0.008
    -
      class: Dist::Zilla::Plugin::ArchiveRelease
      name: '@RSRCHBOY/ArchiveRelease'
      version: 4.00
    -
      class: Dist::Zilla::Plugin::License
      name: '@RSRCHBOY/License'
      version: 4.300028
    -
      class: Dist::Zilla::Plugin::CopyFilesFromBuild
      name: '@RSRCHBOY/CopyFilesFromBuild'
      version: 0.103510
    -
      class: Dist::Zilla::Plugin::ReadmeAnyFromPod
      name: '@RSRCHBOY/ReadmePodInRoot'
      version: 0.120120
    -
      class: Dist::Zilla::Plugin::CPANFile
      name: '@RSRCHBOY/CPANFile'
      version: 4.300028
    -
      class: Dist::Zilla::Plugin::PodWeaver
      name: '@RSRCHBOY/PodWeaver'
      version: 3.101641
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: runtime
          type: requires
      name: Prereqs
      version: 4.300028
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 4.300028
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: 4.300028
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 4.300028
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 4.300028
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 4.300028
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: 4.300028
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 1
    version: 4.300028
